from .connect import Database, DatabaseError